# Introduction to MATLAB

## Section 1: MATLAB Basics

Let's begin by typing stuff into the console and seeing what happens.

### Section 1.1: Arithmetic

Just like with every other programming language, you can use MATLAB as a calculator.  Type the commands you see in the cells marked `In` into your console and press `Enter`; your output should match the `Out` cell directly beneath it.

In [1]:
format compact
1 + 3

ans =
     4


In [2]:
2 * 4

ans =
     8


In [3]:
1/2

ans =
    0.5000


As you would expect, MATLAB respects the order of operations you are used to from math:

In [4]:
20 + 2 / 1 * 2

ans =
    24


In [5]:
(20 + 2) / 1 * 2

ans =
    44


You can save values to variables and do calculations with them.  Note the `;` at the end of each of the lines below: adding a `;` to a statement suppresses output to the console.

In [6]:
x = 20;
y = 7;
x * y - 13

ans =
   127


Note the output: MATLAB stores the result of your last entered command in the variable `ans`.  

In [7]:
ans

ans =
   127


#### Exercise 1.1

You can pull up the documentation on a function by typing `doc <function>` in the console.  Look up the documentation for the `mod` function and answer the following questions.

1. How can you tell when a number is odd?
2. How can you tell when a number is divisible by 10?


### Section 1.2 : Matrices

MATLAB is all about matrices.  Everything is a fucking matrix.  There are several ways to make matrices.  For example, if we wanted to make a row vector of the first 10 integers, we can do...

In [8]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

a =
     1     2     3     4     5     6     7     8     9


The `size` function returns the dimensions of an object.  For example:

In [9]:
size(a)

ans =
     1     9


This means that `a` is a matrix of 1 row and 9 columns.  

You can access elements of a matrix by passing its index:

In [10]:
a(5)

ans =
     5


You can use the `end` keyword to access the last element of a matrix:

In [11]:
a(end)

ans =
     9


You can also access a range of values:

In [12]:
a(2:5)

ans =
     2     3     4     5


You can create a column vector by separating the row entires with a `;`:

In [13]:
b = [10; 11; 12; 13; 14; 15; 16; 17; 18;]

b =
    10
    11
    12
    13
    14
    15
    16
    17
    18


When we call `size` on `b`:

In [14]:
size(b)

ans =
     9     1


When the desired matrix is evenly spaced, we can take advantage of the `:` operator.  The syntax to use the `:` operator is `start:end`.  This will return a row vector of values from `start` to `end`.  For example, to create matrix `a` using the `:` operator, we can do:

In [15]:
a = 1:9

a =
     1     2     3     4     5     6     7     8     9


We can use the transpose (as in matrix transpose) operator `'` to create a column vector.  For example, we can create matrix `b` with the following command:

In [16]:
b = (10:18)'

b =
    10
    11
    12
    13
    14
    15
    16
    17
    18


The `:` operator also accepts an argument for the step size.  The syntax is `start:step:end`.  By default, `step` is set to 1.  Using the `:` operator, we can list the even numbers between 1 and 10 like so:

In [17]:
0:2:10

ans =
     0     2     4     6     8    10


The step size doesn't have to be an integer:

In [18]:
1:0.1:2

ans =
  Columns 1 through 7
    1.0000    1.1000    1.2000    1.3000    1.4000    1.5000    1.6000
  Columns 8 through 11
    1.7000    1.8000    1.9000    2.0000


And we can combine the output of the `:` operator with the transpose operator `'`:

In [19]:
(13:5:39)'

ans =
    13
    18
    23
    28
    33
    38


It may be the case that you know how many values you'd like but you don't know how to evenly space them.  In this case, you can use the `linspace` function.  The syntax for `linspace` is `linspace(start, end, n)`; `linspace` will return a **lin**early **space**d vector of `n` elements from `start` to `end`.  For example, if we wanted a list of 5 elements between 13 and 15:

In [20]:
linspace(13, 15, 5)

ans =
   13.0000   13.5000   14.0000   14.5000   15.0000


You can create matrices of higher dimensions by combining `;` and `,`:

In [21]:
c = [1:3; 4:6; 7:9]

c =
     1     2     3
     4     5     6
     7     8     9


We can access elements of matrix by supply a row and column number.  For instnace, to access the 8 in `c`, we can use:

In [22]:
c(3, 2)

ans =
     8


We can access all the elements along a given dimension by passing `:` to the index.  For instance, to access all the elements in the 2nd column, we can do:

In [23]:
c(:, 2)

ans =
     2
     5
     8


Or the 3rd row:

In [24]:
c(3, :)

ans =
     7     8     9


We can also reshape matrices using the `reshape` function.  The syntax for `reshape` is `reshape(mat, [dim_1, dim_2, ...]`, where `mat` is the matrix to be resized and `[dim_1, dim_2, ... ]` is the row vector of dimensions to resize `mat` to.  For example, we can turn `a` and `b` into 3 by 3 matrices:

In [25]:
a = reshape(a, [3, 3])

a =
     1     4     7
     2     5     8
     3     6     9


In [26]:
b = reshape(b, [3, 3])

b =
    10    13    16
    11    14    17
    12    15    18


#### Exercise 1.2

1. Use the `:` operator to count backwards from 100 in multiples of 3.
2. What happens when you call `c(end)`?  What do you get when you call `c(end)`?  Why?
3. Create a column vector `d` that contains the first 27 integers.  Reshape it into a 3-dimensional square matrix.  Visualize this matrix as a cube.  How would you access the "floor" of the cube?  The middle "slice" of the cube (ie, `[4, 5, 6; 13, 14, 15; 22, 23, 24]`)?  The elements `[19; 22; 25]`? 
4. Change the value in the center of `d` to `pi`.

### Section 1.3: More Ways to Create a Matrix

MATLAB has a few useful MATRIX creation methods.  We can create a matrix of zeros with the `zeros` function:

In [27]:
zeros(2)

ans =
     0     0
     0     0


The argument of `zeros` is the dimensions of the array you want.  When only one integer is passed, `zeros` returns an `n` by `n` matrix.  When we pass more than one integer...

In [28]:
zeros(2, 3)

ans =
     0     0     0
     0     0     0


In [29]:
zeros(3, 3, 3)

ans(:,:,1) =
     0     0     0
     0     0     0
     0     0     0
ans(:,:,2) =
     0     0     0
     0     0     0
     0     0     0
ans(:,:,3) =
     0     0     0
     0     0     0
     0     0     0


...and so on.  Similarly, we can create an identity matrix with the `eye` function.  Like `zeros`, when passed one argument, `eye` will return a square matrix.

In [30]:
eye(5)

ans =
     1     0     0     0     0
     0     1     0     0     0
     0     0     1     0     0
     0     0     0     1     0
     0     0     0     0     1


We can also pass multiple dimensions to `eye`; this will result in a matrix with 1s along the main diagonal and 0s elsewhere.

In [31]:
eye(4, 3)

ans =
     1     0     0
     0     1     0
     0     0     1
     0     0     0


A third function, `rand`, will return a matrix of random values.  

In [32]:
rand(5)

ans =
    0.8147    0.0975    0.1576    0.1419    0.6557
    0.9058    0.2785    0.9706    0.4218    0.0357
    0.1270    0.5469    0.9572    0.9157    0.8491
    0.9134    0.9575    0.4854    0.7922    0.9340
    0.6324    0.9649    0.8003    0.9595    0.6787


In [33]:
x = rand(2, 3)

x =
    0.7577    0.3922    0.1712
    0.7431    0.6555    0.7060


We can use `mean` to find the mean of a matrix along a given dimension.  The syntax for `mean` is `mean(mat, dim)`, where `mat` is the matrix of interest and `dim` is the dimension to take the means along.  For example:

In [34]:
mean(x, 1)

ans =
    0.7504    0.5239    0.4386


So we got a row vector containing the mean of each column.  Similarly, to get a column vector containing the mean of each row, we can do:

In [35]:
mean(x, 2)

ans =
    0.4404
    0.7016


#### Exercise 1.3

1. Look in the documentation for `mean` to see how to find the mean of all the values in `x`.  Why do you think `mean` defaults to operate along a given dimension?
2. Use `std` to take the standard deviation of each column and of each row of `x`.  

### Section 1.4: Matrix Operations

Addition and multiplication between a scalar and a matrix is done componentwise.  For example:

In [36]:
a

a =
     1     4     7
     2     5     8
     3     6     9


In [37]:
2 + a

ans =
     3     6     9
     4     7    10
     5     8    11


In [38]:
a * 3

ans =
     3    12    21
     6    15    24
     9    18    27


You can add and subtract equally-sized matrices from each other:

In [39]:
a + b

ans =
    11    17    23
    13    19    25
    15    21    27


In [40]:
a - 2 * b

ans =
   -19   -22   -25
   -20   -23   -26
   -21   -24   -27


We can do matrix multiplication between two matrices whose inner dimensions are equal:

In [41]:
a * b

ans =
   138   174   210
   171   216   261
   204   258   312


MATLAB also supports componentwise multiplication:

In [44]:
a .* b

ans =
    10    52   112
    22    70   136
    36    90   162


[Previous Section: Introduction](p3.matlab.fall2018-00.ipynb)<br>
[Next Section: Application: Functions](p3.matlab.fall2018-02.ipynb)